#+ summary: Returns the number of patients in the registry with the corresponding disease code
#+ tags:
#+   - Patient Count
#+ defaults:
#+   - type: http://www.orpha.net/ORDO/Orphanet_98896
#+ endpoint_in_url: False

PREFIX sio: <http://semanticscience.org/resource/>
select (count(?p) as ?count) where { 
    ?p sio:SIO_000228 ?role .  # person has role role
    ?role sio:SIO_000356 ?process . # is realized in process
    ?process sio:SIO_000229 ?output . #has output output
    ?output sio:SIO_000628 ?attribute . # output refers to attribute
	?attribute a <http://www.orpha.net/ORDO/Orphanet_98896> .  # attribute is a orphacode
}
