#+ summary: Returns the Key Performance Indicator of the delay between symptom onset and diagnosis.  This data is aggregated by disease, and by year of diagnosis, and is measured in days.
#+ tags:
#+ - KPI diagnosis-delay
#+ defaults:
#+ 
#+ endpoint_in_url: False

################################################################
# list diagnosis and time from onset to diagnosis
################################################################

PREFIX sio: <http://semanticscience.org/resource/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ofn: <http://www.ontotext.com/sparql/functions/>

SELECT DISTINCT ?ORDO ?yearOfDiagnosis (xsd:integer(ROUND(AVG(?timeOnsetToDiagnosis))) as ?avgoffset)
WHERE {
    BIND(xsd:integer(ofn:asDays(?onsetdate - ?diagnosisdate)) AS ?timeOnsetToDiagnosis)
#    BIND(xsd:integer(ofn:asDays(?diagnosisdate - ?onsetdate)) AS ?timeOnsetToDiagnosis)
    BIND(SUBSTR(str(?diagnosisdate), 1,4) AS ?yearOfDiagnosis)
    {
        SELECT  ?ORDO ?diagnosisdate WHERE {
            GRAPH ?g {
                ?person sio:SIO_000228 ?role1 .  # person has role role
                ?role1 sio:SIO_000356 ?process1 . # is realized in process
                ?process1 a <http://purl.obolibrary.org/obo/NCIT_C18020> .  # diagnostic process
                ?process1 sio:SIO_000229 ?output1 . #has output output 
                ?output1 a <http://purl.obolibrary.org/obo/NCIT_C154625> .  # diagnosis code
                ?output1 sio:SIO_000628 ?diagnosis1 . # output refers to attribute
                ?diagnosis1 a ?ORDO .
                FILTER(!(?ORDO = sio:SIO_000614)) .  # not an "attribute" diagnosis
	    	}
    		?g sio:SIO_000680 ?startdate .
    		?startdate sio:SIO_000300 ?diagnosisdate .
        }
    }
    {
        SELECT  ?onsetdate WHERE {
            ?person sio:SIO_000228 ?role2 .  # person has role role
            ?role2 sio:SIO_000356 ?process2 . # is realized in process
            ?process2 sio:SIO_000229 ?output2 . #has output output
            ?output2 sio:SIO_000300 ?onsetdate .
            ?output2 sio:SIO_000628 ?attribute2 . # output refers to attribute
            ?attribute2 a <http://purl.obolibrary.org/obo/NCIT_C124353> .   
        }
    }
} group by ?ORDO ?yearOfDiagnosis order by ?yearOfDiagnosis ?ORDO

