#+ summary: Returns the Key Performance Indicator of the delay between symptom onset and diagnosis.  This data is aggregated by disease, and by year of diagnosis, and is measured in days.
#+ tags:
#+ - KPI diagnosis-delay
#+ defaults:
#+ 
#+ endpoint_in_url: False

################################################################
# list diagnosis and time from onset to diagnosis
################################################################
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ordo: <http://www.orpha.net/ORDO/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ofn: <http://www.ontotext.com/sparql/functions/>

# date of symptom onset is the value (output) of its own model, date of diagnosis is in the context of the diagnosis model
#SELECT DISTINCT ?pid ?onsetvalue ?diagnosisdate ?ORDO ?yearOfDiagnosis (xsd:integer(ROUND(AVG(?timeOnsetToDiagnosis))) as ?avgoffset)
SELECT DISTINCT ?ORDO ?yearOfDiagnosis (xsd:integer(ROUND(AVG(?timeOnsetToDiagnosis))) as ?avgoffset)
WHERE {
    BIND(xsd:integer(ofn:asDays(?diagnosisdate - ?onsetvalue )) AS ?timeOnsetToDiagnosis)
    BIND(SUBSTR(str(?diagnosisdate), 1,4) AS ?yearOfDiagnosis)
    
		GRAPH ?diseasegraph {
#        ?person sio:SIO_000228 ?role .   # this is the patient/ID model
#        ?id sio:SIO_000020 ?role .
#        ?id sio:SIO_000300 ?pid .
                ?disperson sio:SIO_000228 ?disrole .  # person has role role
        		?id        sio:SIO_000020 ?disrole .  # identifier denotes role

        		# THE JOIN IS BEING DONE AROUND ?patientid!!!
                ?id        sio:SIO_000300 ?patientid .  # has  value
                ?disrole sio:SIO_000356 ?disprocess ;  # is realized in process
                            a sio:SIO_000016 .
                ?disprocess a  <http://purl.obolibrary.org/obo/NCIT_C18020> ; # diagnostic process
                                sio:SIO_000229 ?disoutput .
                ?disoutput a <http://purl.obolibrary.org/obo/NCIT_C154625>; # diagnosis code
                                sio:SIO_000628 ?disattribute.
                ?disattribute a ?ORDO.
        FILTER(!(?ORDO = sio:SIO_000614))
        }
        ?diseasegraph a obo:NCIT_C62143 ; # encounter
    			sio:SIO_000068 ?diseasetimeline, ?diseaseevent ; # is part of
    			sio:SIO_000680 ?diseasestartdate . # start date
    	?diseasestartdate sio:SIO_000300 ?diagnosisdate .  # need the has value property

# date of symptom onset is the value (output) of its own model, date of diagnosis is in the context of the diagnosis model
        GRAPH ?onsetg {
            ?id        sio:SIO_000020 ?onsetrole .  # identifier denotes role
            ?id        sio:SIO_000300 ?patientid .   # has value
            ?onsetrole sio:SIO_000356 ?onsetprocess ; 
                        a sio:SIO_000016 .
            ?onsetprocess a sio:SIO_000006 , ?onsetprocess_type ; 
                        sio:SIO_000229 ?onsetoutput .
            ?onsetoutput a sio:SIO_000015, ?onsetoutput_type; 
                        sio:SIO_000628 ?onsetattribute.
            ?onsetattribute a  <http://purl.obolibrary.org/obo/NCIT_C124353>.
        	
            ?onsetoutput sio:SIO_000300 ?onsetvalue .
        }
        ?onsetg a obo:NCIT_C62143 ; # encounter
	        sio:SIO_000068 ?onsettimeline, ?onsetevent . # is part of

} group by ?ORDO ?yearOfDiagnosis order by ?yearOfDiagnosis ?ORDO 


